#!/bin/sh
# sync.sh — canonical config sync for Claude Code and Codex.
#
# Renders sync/core.md + sync/overlay.<host>.md into each host's instruction
# file, substituting {{VAR}} from sync/vars.<host>.
#
# Owns:    CLAUDE.md, AGENTS.md, sync/hooks symlinks, codex skill symlinks.
# Audits:  settings.json, config.toml, hooks.json — never edits them.
set -u

SYNC="$HOME/.claude/sync"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
CODEX_MD="$HOME/.codex/AGENTS.md"
HDR='<!-- GENERATED by ~/.claude/sync/sync.sh — edit sync/core.md or sync/overlay.*.md, not this file -->'

# Skills installed for Claude but not Codex. The reciprocal pair `codex`
# (Claude-only) and `gstack-claude` (Codex-only) is deliberately absent: those
# are the outside-voice skill on each host and must stay asymmetric.
SKILL_GAP='_gstack-command connect-chrome docx emil-design-eng expo-native-ui
expo-router expo-web-to-native find-skills gemini-media higgsfield-generate
higgsfield-soul-id higgsfield-video-explainer humanizer impeccable pptx
react-native-best-practices xlsx'

render() { # <vars> <core> <overlay> <out>
  _v=$1; _c=$2; _o=$3; _out=$4
  [ -f "$_v" ] || { echo "sync: no vars file $_v" >&2; return 1; }
  [ -f "$_c" ] || { echo "sync: no core file $_c" >&2; return 1; }
  [ -f "$_o" ] || { echo "sync: no overlay file $_o" >&2; return 1; }
  _tmp=$(mktemp)
  { printf '%s\n\n' "$HDR"; cat "$_c"; printf '\n'; cat "$_o"; } > "$_tmp"
  while IFS='=' read -r k val; do
    case "$k" in ''|\#*) continue ;; esac
    esc=$(printf '%s' "$val" | sed 's/[&|\\]/\\&/g')
    # Portable in-place edit: BSD and GNU sed disagree on -i, so avoid it.
    sed "s|{{$k}}|$esc|g" "$_tmp" > "$_tmp.n" && mv "$_tmp.n" "$_tmp"
  done < "$_v"
  if grep -q '{{[A-Z_]*}}' "$_tmp"; then
    echo "sync: unbound variable(s) rendering $_c:" >&2
    grep -o '{{[A-Z_]*}}' "$_tmp" | sort -u >&2
    rm -f "$_tmp"; return 1
  fi
  mv "$_tmp" "$_out"
}

usage() {
  cat >&2 <<'EOF'
usage: sync.sh <command>
  apply        regenerate both hosts' instruction files and link skills
  --check      report drift and audit settings; nonzero exit on any gap
  link-skills  create missing codex skill symlinks only
  render <vars> <core> <overlay> <out>
EOF
  exit 2
}

case "${1:-}" in
  render) shift; render "$@" ;;
  *) usage ;;
esac
