#!/bin/sh
# sync.sh — canonical config sync for Claude Code and Codex.
#
# Renders sync/core.md + sync/overlay.<host>.md into each host's instruction
# file, substituting {{VAR}} from sync/vars.<host>.
#
# Owns:    CLAUDE.md, AGENTS.md, sync/hooks symlinks, codex skill symlinks.
# Audits:  settings.json, config.toml, hooks.json — never edits them.
set -u

SYNC="$HOME/.claude/sync"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
CODEX_MD="$HOME/.codex/AGENTS.md"
HDR='<!-- GENERATED by ~/.claude/sync/sync.sh — edit sync/core.md or sync/overlay.*.md, not this file -->'

# Skills installed for Claude but not Codex. The reciprocal pair `codex`
# (Claude-only) and `gstack-claude` (Codex-only) is deliberately absent: those
# are the outside-voice skill on each host and must stay asymmetric.
SKILL_GAP='_gstack-command connect-chrome docx emil-design-eng expo-native-ui
expo-router expo-web-to-native find-skills gemini-media higgsfield-generate
higgsfield-soul-id higgsfield-video-explainer humanizer impeccable pptx
react-native-best-practices xlsx'

render() { # <vars> <core> <overlay> <out>
  _v=$1; _c=$2; _o=$3; _out=$4
  [ -f "$_v" ] || { echo "sync: no vars file $_v" >&2; return 1; }
  [ -f "$_c" ] || { echo "sync: no core file $_c" >&2; return 1; }
  [ -f "$_o" ] || { echo "sync: no overlay file $_o" >&2; return 1; }
  _tmp=$(mktemp)
  { printf '%s\n\n' "$HDR"; cat "$_c"; printf '\n'; cat "$_o"; } > "$_tmp"
  while IFS='=' read -r k val; do
    case "$k" in ''|\#*) continue ;; esac
    esc=$(printf '%s' "$val" | sed 's/[&|\\]/\\&/g')
    # Portable in-place edit: BSD and GNU sed disagree on -i, so avoid it.
    sed "s|{{$k}}|$esc|g" "$_tmp" > "$_tmp.n" && mv "$_tmp.n" "$_tmp"
  done < "$_v"
  if grep -q '{{[A-Z_]*}}' "$_tmp"; then
    echo "sync: unbound variable(s) rendering $_c:" >&2
    grep -o '{{[A-Z_]*}}' "$_tmp" | sort -u >&2
    rm -f "$_tmp"; return 1
  fi
  mv "$_tmp" "$_out"
}

# Symlink the gap skills into Codex. ~/.claude/skills is canonical — the copies
# under ~/.agents/skills have diverged and some carry empty SKILL.md files.
link_skills() {
  [ -d "$HOME/.codex/skills" ] || { echo "  note: ~/.codex/skills absent, skipped"; return 0; }
  _made=0; _skip=0; _bad=0
  for s in $SKILL_GAP; do
    _src="$HOME/.claude/skills/$s"
    _dst="$HOME/.codex/skills/$s"
    if [ ! -s "$_src/SKILL.md" ]; then
      echo "  warn: $s has no readable SKILL.md, not linked" >&2; _bad=$((_bad + 1)); continue
    fi
    # Never clobber a real directory Codex owns; only manage our own symlink.
    if [ -e "$_dst" ] && [ ! -L "$_dst" ]; then
      echo "  warn: $s exists as a real dir in codex, left alone" >&2; _bad=$((_bad + 1)); continue
    fi
    if [ -L "$_dst" ] && [ "$(readlink "$_dst")" = "$_src" ]; then
      _skip=$((_skip + 1)); continue
    fi
    ln -sfn "$_src" "$_dst" && _made=$((_made + 1))
  done
  echo "  skills: $_made linked, $_skip already current, $_bad skipped"
  [ "$_bad" -eq 0 ]
}

apply() {
  render "$SYNC/vars.claude" "$SYNC/core.md" "$SYNC/overlay.claude.md" "$CLAUDE_MD" || return 1
  echo "  wrote $CLAUDE_MD"
  if [ -d "$HOME/.codex" ]; then
    render "$SYNC/vars.codex" "$SYNC/core.md" "$SYNC/overlay.codex.md" "$CODEX_MD" || return 1
    echo "  wrote $CODEX_MD"
    link_skills || return 1
  else
    echo "  note: ~/.codex absent, skipped"
  fi
}

# Report drift without touching anything. Exit 1 if any gap is found.
# Never dumps config.toml or settings.json — they hold MCP tokens and API keys;
# only counts and yes/no answers come out.
check() {
  _gaps=0
  echo "drift:"
  _t=$(mktemp)
  if render "$SYNC/vars.claude" "$SYNC/core.md" "$SYNC/overlay.claude.md" "$_t" 2>/dev/null &&
     cmp -s "$_t" "$CLAUDE_MD"; then
    echo "  ok   CLAUDE.md matches the template"
  else
    echo "  GAP  CLAUDE.md differs from the template — run: sync.sh apply"; _gaps=$((_gaps + 1))
  fi
  if [ -d "$HOME/.codex" ]; then
    if render "$SYNC/vars.codex" "$SYNC/core.md" "$SYNC/overlay.codex.md" "$_t" 2>/dev/null &&
       cmp -s "$_t" "$CODEX_MD"; then
      echo "  ok   AGENTS.md matches the template"
    else
      echo "  GAP  AGENTS.md differs from the template — run: sync.sh apply"; _gaps=$((_gaps + 1))
    fi
  fi
  rm -f "$_t"

  echo "hooks:"
  for _h in block-secret-reads.sh marcel-detector.sh; do
    if [ -L "$HOME/.claude/hooks/$_h" ]; then
      echo "  ok   claude/$_h -> shared copy"
    else
      echo "  GAP  claude/$_h is not a symlink to sync/hooks"; _gaps=$((_gaps + 1))
    fi
  done
  _cg="$HOME/.codex/hooks/block-secret-reads.sh"
  if [ -L "$_cg" ] && cmp -s "$_cg" "$SYNC/hooks/block-secret-reads.sh"; then
    echo "  ok   codex guard is the shared copy"
  else
    echo "  GAP  codex guard is stale or missing — the Keys store is underprotected"; _gaps=$((_gaps + 1))
  fi

  echo "skills:"
  _missing=0
  for _s in $SKILL_GAP; do
    [ -e "$HOME/.codex/skills/$_s" ] || _missing=$((_missing + 1))
  done
  if [ "$_missing" -eq 0 ]; then
    echo "  ok   all shared skills present on codex"
  else
    echo "  GAP  $_missing skill(s) not linked — run: sync.sh link-skills"; _gaps=$((_gaps + 1))
  fi

  # Audit only: these files have different vendor schemas, so sync.sh reports on
  # them and never edits them. Acting on what it says is a human decision.
  echo "settings audit (report only, never edited):"
  _dn=$(grep -c 'Keys' "$HOME/.claude/settings.json" 2>/dev/null || echo 0)
  echo "  claude: $_dn deny-rule line(s) mention the Keys store"
  if [ -f "$HOME/.codex/config.toml" ]; then
    if grep -qE '^\s*(deny|denied|block)' "$HOME/.codex/config.toml" 2>/dev/null; then
      echo "  codex:  config.toml has deny-style entries"
    else
      echo "  codex:  config.toml has NO deny mechanism — the shared hook guard is"
      echo "          the only thing protecting the Keys store on this host"
    fi
  fi
  if [ -f "$HOME/.codex/hooks.json" ]; then
    grep -q block-secret-reads "$HOME/.codex/hooks.json" && echo "  codex:  guard wired in hooks.json" \
      || { echo "  GAP  codex hooks.json does not call the guard"; _gaps=$((_gaps + 1)); }
    grep -q UserPromptSubmit "$HOME/.codex/hooks.json" && echo "  codex:  marcel-detector wired in hooks.json" \
      || echo "  note:  marcel-detector not wired on codex"
  fi

  [ "$_gaps" -eq 0 ] && echo "in sync." || echo "$_gaps gap(s) found."
  [ "$_gaps" -eq 0 ]
}

usage() {
  cat >&2 <<'EOF'
usage: sync.sh <command>
  apply        regenerate both hosts' instruction files and link skills
  --check      report drift and audit settings; nonzero exit on any gap
  link-skills  create missing codex skill symlinks only
  render <vars> <core> <overlay> <out>
EOF
  exit 2
}

case "${1:-}" in
  render) shift; render "$@" ;;
  apply) apply ;;
  link-skills) link_skills ;;
  --check|check) check ;;
  *) usage ;;
esac
